name: ohoexperience_dart

description: A sample command-line application.

version: 1.0.0

repository: https://github.com/ohoexperience/dart_address.git

# resolution: workspace

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  melos: ^6.1.0
  test: ^1.24.0
